Moved gradebook calculation methods from view to utils.
ExtensionEngine/gradebook-edx-platform-extensions pull request #4
Opened 2017-12-08 10:37 UTC by iivic

We need the gradebook calculation in edx platform. It makes sense
to move and create the calculation methods/functions in utils file
so they can be used elsewhere without calling the class.

NDPD-740

Note: I ran isort.

2017-12-11 13:34 UTC, marjev requested changes
Just move the gradebook calculation methods to the utils.py.

Don't introduce weird coupling. Also, utils.py should contain a method that will be used to generate a CSV report.

2017-12-11 13:34 UTC, marjev commented on gradebook/views.py
> +from xmodule.modulestore.django import modulestore
Regroup the imports like this:
- python packages
- 3rd party packages
- project packages

2017-12-11 13:34 UTC, marjev commented on gradebook/utils.py
> +    }
This method is completely unnecessary and introduces a possible landmine in the code for any future changes.

This PR should only move the methods from the class into the `utils.py`.

If a method like this should exist, it's certainly not something that a gradebook utils file should have in it.

2017-12-11 14:22 UTC, iivic commented on gradebook/utils.py
> +    }
I think that this method is a nice way to dry all the function calls needed to retrieve grade summaries. I can't see how it introduces "possible landmine" since it uses the functions needed to get grade summaries, any change in those functions will be reflected here and we can make changes according to our needs.

Your statements "This PR should only move the methods from the class into the utils.py." and "utils.py should contain a method that will be used to generate a CSV report." are contradictory.

Since this function is used with get_grade_sammaries it should be in the same file as the mentioned function.

I can't see any downsides to this function. Can you provide an example why this is a bad idea so I can avoid introducing weird coupling?

2017-12-11 16:19 UTC, marjev commented on gradebook/utils.py
> +    }
I'll take over this work. You can work on other instructor related stuff.

2017-12-12 09:19 UTC, marjev commented
@iivic review the code

2017-12-12 13:03 UTC, iivic reviewed
LGTM. Don't forget to squash.

2017-12-12 13:59 UTC, marjev approved these changes

2017-12-12 14:00 UTC, merged